Repository snehaljha/local-tomcat, pull requests merged in 2022-10, with the labels that each got.

#2 Edited Readme.md
  README.md
Labels: hacktoberfest-accepted

#3 Update README.md
  README.md
Labels: hacktoberfest-accepted

#4 Features
  README.md
Labels: hacktoberfest-accepted

#6 added enhanced comment
  src/test/suite/index.ts
Labels: hacktoberfest-accepted

#7 Update deployer.ts
  src/util/deployer.ts
Labels: bug, hacktoberfest-accepted

#8 Update README.md
  README.md
Labels: good first issue, hacktoberfest-accepted

#9 Update extension.ts
  src/extension.ts
Labels: bug, hacktoberfest-accepted
